- internal/shim-sev/src/syscall.rs
- tests/bin/libc.h
- tests/bin/readv.c
- tests/integration_tests.rs
> shim-sev: Implement readv as multiple read for now

- src/sallyport/mod.rs
- tests/integration_tests.rs
> FIXME: Expand sallyport block size

- .github/workflows/test.yml
- Cargo.toml
- src/backend/mod.rs
- src/main.rs
> Gate backends behind features

- src/backend/sev/mod.rs
Closes: #14 
Looks like this:
```console
$ cargo run info
[..]
✔ MEMLOCK rlimit allows for: ~1638 keeps (soft limit = 8589934592 bytes, hard limit = 8589934592 bytes)
```
Or on a machine that can't meet this requirement:
```console
$ cargo run info
[..]
✗ MEMLOCK rlimit allows for: 0 keeps (soft limit = 65536 bytes, hard limit = 65536 bytes)
The MEMLOCK rlimit must be large enough to accommodate the Enarx shim, wasmldr, and the memory pressure requirements of the target workloads across all deployed SEV keeps.
```
> Incorporate memlock rlimit check into SEV-readiness

- internal/shim-sev/build.rs
- internal/shim-sev/src/start.S
Set stack size according to rust profile
> Set stack size according to rust profile

- internal/rcrt1/src/lib.rs
If DT_REL or DT_RELA is not specified in the dynamic section,
don't attempt to do anything, although it should have been safe,
as the size was set to `0` still.
> rcrt1: safe-guard against unset DT_REL or DT_RELA

- .github/workflows/enarxbot.yml
In addition to being easier to maintain and share, this should provide some nice speed benefits.
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>
> Enable event-based Enarxbot v2

- README.md
- src/main.rs
Closes: https://github.com/enarx/enarx/issues/925
> Document how to select a different backend

- tests/bin/get_att.c
- tests/bin/libc.h
- tests/integration_tests.rs
> Create a test for the getatt() syscall that should return ENOSYS

- internal/shim-sev/src/frame_allocator.rs
- src/sallyport/mod.rs
* sallyport: return `OutOfSpace` Error
This patch silences the `result_unit_err` clippy warning.
https://rust-lang.github.io/rust-clippy/master/index.html#result_unit_err
Instead of returning unit `()` as Error for `Cursor::alloc` and similar
methods, introduce a new type `OutOfSpace`, indicating that the current
Block does not have enough place for the requested operation.
Related: https://github.com/enarx/enarx-keepldr/pull/95#issuecomment-716500220
* shim-sev: Return `AllocateError` for `FrameAllocator` methods
This patch silences the result_unit_err clippy warning.
https://rust-lang.github.io/rust-clippy/master/index.html#result_unit_err
Instead of returning unit () as Error for the `FrameAllocator` methods,
return a specific `AllocateError` enum.
> Silence result_unit_err clippy warning

- tests/bin/getuid.c
- tests/bin/libc.h
- tests/integration_tests.rs
Closes #93.
Signed-off-by: Adam Baxter <ambaxter@users.noreply.github.com>
> Add getuid syscall test

- internal/shim-sgx/src/handler.rs
> shim-sgx: fence cpuid host syscall

- .github/workflows/enarxbot.yml
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>
> Set BOT_TOKEN separately for compatibility with new Enarxbot revisions

- internal/shim-sev/src/hostcall.rs
- internal/shim-sgx/src/handler.rs
> shims: correct fencing comments

- internal/shim-sev/src/syscall.rs
Revert the previous patch and introduce a much simpler one.
shim-sev: handle multiple return values for syscalls
`rdx` is sometimes used as a secondary return value.
This patch lets `syscall_rust` return a double u64 struct instead of u64,
which will use `rax` for the first 64 bits and `rdx` for the last 64 bit.
Because `rdx` is not marked as `clobber` for the musl syscall macro,
the original value has to be returned, if `rdx` is unused as a return
value.
This patch also adds a dummy path for the enarx syscalls, which can make
use of the second return value.
> rework of shim-sev: handle multiple return values for syscalls

- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/event.rs
- internal/shim-sgx/src/handler.rs
- tests/bin/get_att.c
> Code => shim stub for getatt() syscall in SGX

- tests/bin/getegid.c
- tests/bin/geteuid.c
- tests/bin/getgid.c
- tests/bin/libc.h
- tests/integration_tests.rs
Closes #105
Signed-off-by: Adam Baxter <ambaxter@users.noreply.github.com>
> Add geteuid, getgid, getegid tests

- internal/syscall/src/lib.rs
- tests/bin/close.c
- tests/bin/libc.h
- tests/integration_tests.rs
> Add close syscall test

- .github/workflows/enarxbot.yml
enarx/bot#160
Adding this LABEL property to the workflow file should allow for distinction between badges on the enarx/bot README.
> Add 'LABEL' to workflow

- tests/integration_tests.rs
> Add missing #[serial] attribute to test

- src/sallyport/mod.rs
This patch let's `Cursor::write` return a mutable reference
to the written element, in case the reference is needed later on.
> feat(sallyport): let `Cursor::write` return a mutable reference

- internal/shim-sev/src/allocator.rs
Handling of physical addresses > 1 << C-Bit would be tricky,
so just limit the maximum.
> fix(shim-sev): Max physical memory determined by C-Bit

- internal/syscall/src/lib.rs
- tests/bin/bind.c
- tests/bin/libc.h
- tests/bin/listen.c
- tests/bin/socket.c
- tests/bin/unix_echo.rs
- tests/integration_tests.rs
Implemented proxying of the following syscalls:
* socket
* bind
* connect
* accept
* accept4
* listen
* recvfrom
> feat(syscall): Add some network syscalls

- Cargo.lock
- internal/shim-sev/Cargo.lock
- internal/shim-sgx/Cargo.lock
> build(deps): Manual cargo update

- Cargo.lock
- Cargo.toml
- src/backend/sev/builder.rs
- src/backend/sev/unattested_launch.rs
> Switch to ciborium

- internal/syscall/src/lib.rs
* pipe
* fcntl with F_GETFD, F_SETFD, F_GETFL, F_SETFL
* ioctl with FIONBIO
* getsockname
* sendto
* setsockopt
* getpid
The dept issue for the integration_tests is: https://github.com/enarx/enarx-keepldr/issues/260
> Add various syscalls for networking

- internal/syscall/src/lib.rs
add the following syscalls:
* epoll_create1
* epoll_ctl
* epoll_wait and epoll_pwait
As a security technical dept, I opened 
Related: https://github.com/enarx/enarx-keepldr/issues/262
Resolves: https://github.com/enarx/enarx-keepldr/issues/259
> Add epoll syscalls

- internal/shim-sev/Cargo.lock
- internal/shim-sev/Cargo.toml
- internal/shim-sev/src/asm.rs
- internal/shim-sev/src/main.rs
Fix for the relevant breaking changes made to x86_64 from 0.12.3 to 0.13.1.
> bump x86_64 from 0.12.3 to 0.13.1

- internal/shim-sev/src/print.rs
`is_printing_enabled` returned the inverse boolean.
Also rename `SHIM_CAN_PRINT` to `PRINT_INHIBITOR` to reflect its usage.
> fix(shim-sev): invert is_printing_enabled

- internal/syscall/src/file.rs
- internal/syscall/src/lib.rs
> feat(syscall): add eventfd2 and dup* syscalls

- .github/workflows/lint.yml
- Cargo.toml
- tests/bin/memspike.rs
> feat(clippy): add clippy for the integration tests

- internal/shim-sev/Cargo.toml
- internal/shim-sgx/Cargo.toml
Optimize for size.
* smaller binary to load
* less to measure
* fits better in cache lines
> feat(shim): optimize for size

- Cargo.lock
- Cargo.toml
- internal/shim-sev/src/paging.rs
- internal/shim-sev/src/syscall.rs
- src/backend/sev/builder.rs
- src/backend/sev/mod.rs
- src/backend/sev/unattested_launch.rs
- tests/integration_tests.rs
These commits lets milan pass our test suite with non-SNP SEV.
> Enable normal SEV on Milan 

- build.rs
> feat: don't build shims not feature enabled

- Cargo.lock
- Cargo.toml
- build.rs
- internal/shim-sev/Cargo.lock
- internal/shim-sev/Cargo.toml
- internal/shim-sev/layout.ld
- internal/shim-sev/src/allocator.rs
- internal/shim-sev/src/hostmap.rs
- internal/shim-sev/src/main.rs
- internal/shim-sgx/Cargo.lock
- internal/shim-sgx/Cargo.toml
- internal/shim-sgx/layout.ld
- internal/shim-sgx/src/main.rs
- src/backend/kvm/mod.rs
- src/backend/kvm/vm/builder.rs
- src/backend/mod.rs
- src/backend/sgx/mod.rs
- src/binary/component.rs
- src/main.rs
Depends on: https://github.com/enarx/sallyport/pull/10
> Use the new sallyport semver versioning

- Cargo.lock
- Cargo.toml
- internal/shim-sev/Cargo.lock
- internal/shim-sgx/Cargo.lock
- internal/shim-sgx/Cargo.toml
- internal/shim-sgx/src/ssa.rs
- src/backend/sgx/enclave/execute.rs
- src/backend/sgx/enclave/mod.rs
- src/backend/sgx/mod.rs
This boils down to two dependency bumps: sgx and x86_64.
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>
> Fix broken build

- Cargo.lock
- Cargo.toml
- src/backend/sgx/data.rs
- src/backend/sgx/enclave/builder.rs
- src/backend/sgx/enclave/ioctls.rs
- src/backend/sgx/mod.rs
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>
> Update to the latest sgx crate commit

- .github/workflows/lint.yml
- .github/workflows/test.yml
- build.rs
This works around this bug:
https://github.com/rust-lang/rust/issues/89432
> Pin to nightly-2021-09-30

- .github/workflows/lint.yml
- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- internal/shim-sev/Cargo.lock
- internal/shim-sev/Cargo.toml
- internal/shim-sev/layout.ld
- internal/shim-sev/src/addr.rs
- internal/shim-sev/src/allocator.rs
- internal/shim-sev/src/gdt.rs
- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/hostmap.rs
- internal/shim-sev/src/payload.rs
- internal/shim-sgx/Cargo.lock
- internal/shim-sgx/Cargo.toml
- src/backend/binary.rs
- src/backend/kvm/builder.rs
- src/backend/kvm/config.rs
- src/backend/kvm/data.rs
- src/backend/kvm/mem.rs
- src/backend/kvm/mod.rs
- src/backend/kvm/thread.rs
- src/backend/mod.rs
- src/main.rs
implementing the new loader traits
Signed-off-by: Harald Hoyer <harald@profian.com>
> feat: re-add the kvm backend

- .github/workflows/lint.yml
- .github/workflows/test.yml
- build.rs
- rust-toolchain
- rust-toolchain.toml
Everything has been fixed upstream.
> Restore building against nightly
