- .github/workflows/lint.yml
- deny.toml
As it turns out, `cargo deny` is now packaged as its own Github Action. Instead of spinning up our own `deny` install, I'm using that.
The `deny` config is identical to the one that was present in `enarx/enarx`, with the addition of explicitly accepting ISC licenses.
Resolves https://github.com/enarx/enarx/issues/909.
> Enforce cargo deny for licenses

- .github/dependabot.yml
As discussed in today's standup. It's currently set to run daily.
Resolves #30.
> Enable dependabot version updates for Cargo

- internal/shim-sev/src/syscall.rs
Do not leak any register contents.
> shim-sev: save and restore rcx and r11 for syscalls

- build.rs
> Let cargo print a warning, if `strip` fails.

- Cargo.lock
- Cargo.toml
- src/backend/sev/builder.rs
Recent changes to the `sev` crate make finding a cached SEV certificate chain very easy as long as it's stored in the conventional search paths it expects.
> Improve SEV chain ergonomics

- README.md
- rust-toolchain
- src/main.rs
Rustup will automatically use the toolchain version described in this file, meaning we no longer have to instruct people to use a nightly override by hand.
> Check in a toolchain file that rustup is aware of

- .github/workflows/lint.yml
> Use a matrix for `cargo deny` to cover the subcrates

- Cargo.lock
- Cargo.toml
- build.rs
Use `walkdir::WalkDir` to traverse the directories.
Add all crates in `./internal/` to rerun-if-changed.
> build.rs: pickup more rerun-if-changed

- internal/shim-sev/src/main.rs
In case of a panic, we force get `HOST_CALL` mutex to print the panic
message.
> shim-sev: unlock hostcall to print PanicInfo

- src/backend/kvm/vm/cpu.rs
For debugging this info is crucial.
> keepldr(kvm/sev): do a register dump on unexpected shutdown

- Cargo.lock
- internal/shim-sev/Cargo.lock
- internal/shim-sev/Cargo.toml
- internal/shim-sev/src/frame_allocator.rs
- internal/shim-sev/src/gdt.rs
- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/lazy.rs
- internal/shim-sev/src/main.rs
- internal/shim-sev/src/paging.rs
- internal/shim-sev/src/payload.rs
- internal/shim-sev/src/print.rs
Use a similar `Lazy` as the experimental `std::lazy::Lazy`.
lazy_static is unmaintained.
> switch away from lazy_static

- build.rs
- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/event.rs
- internal/shim-sgx/src/handler.rs
- tests/bin/echo.rs
- tests/integration_tests.rs
This builds any `tests/bin/*.rs` found, which can be used for
integration tests.
A simple `echo.rs` test writing every `stdin` to `stdout` is added.
Because this uses `poll`, the `poll` syscall was also implemented for
the `sgx` and `sev` shims.
> Execute a simple `echo` rust test program.

- src/main.rs
Closes #63.
Before the patch:
$ ps aux | grep enarx-keepldr
// empty, aside from grep process
$ ps aux | grep demo
[..] /home/ckuehl/src/demo/target/debug/demo
// have to grep for 'demo' as process name
After the patch:
$ ps aux | grep enarx-keepldr
[..] target/debug/enarx-keepldr /home/ckuehl/src/demo/target/debug/demo
// grepping for 'enarx-keepldr' will find the process
> Retain 'enarx-keepldr' as process name for nil keep

- Cargo.lock
- Cargo.toml
- tests/integration_tests.rs
The `process_control` crate allows to get the output while waiting.
Otherwise the child stderr/stderr buffers may fillup, the test process
would block, and will finally be killed by `run_test()`.
> tests: use `process_control` to wait with timeout

- README.md
- README.tpl
Closes #85 
Added a badge to the README to reflect the status of enarx/bot
> Added enarx/bot status badge

- internal/sallyport/src/lib.rs
- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/handler.rs
- src/backend/kvm/vm/cpu.rs
- src/sallyport/mod.rs
* shims: Add a compiler memory fence for the host proxy calls
To prevents the compiler from optimizing read and writes not knowing of
the side-effects of the syscall, `core::sync::atomic::compiler_fence`
is added before and after the host call via sallyport.
Therefore this patch also changes the now unnecessary volatile
writes into normal writes.
Fixes: https://github.com/enarx/enarx-keepldr/issues/59   
* sallyport: Re-enable tests
Re-enable the test suite by temporarily changing the
`Block::buf_capacity` to `Page::size()` if tests are enabled,
otherwise the tests will fail with a buffer overflow.
Also ignore the `syscall` test for `cargo miri test`, because
inline assembly is not supported for `miri`.
* sallyport: Extend `Cursor` with read/write convenience methods
This patch extends …
> Improve the sallyport cursor data handling

- internal/shim-sev/src/syscall.rs
Swap the `gs` register back to user space `gs` _after_ the kernel
handled the syscall.
Later `gs` can be used for other purposes in the kernel, so this
prevents future usage to clobber userspace `gs` in any way.
> shim-sev:syscall: swapgs at end of syscall

- tests/bin/libc.h
Otherwise we segfault when we access it for some reason...
> Remove __thread storage class from errnum

- internal/shim-sev/build.rs
According to
https://github.com/enarx/enarx-keepldr/pull/102#issuecomment-714803978
the `-mtune=znver2` switch requires a backported patch. Because this
optimization flag is not really needed, just remove it.
> shim-sev:build.rs: remove problematic opt flag

- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/syscall.rs
* shim-sev:syscall: Add the C arguments to the syscalls
This patch adds the C arguments to the syscalls to match the signature
of the C functions. This improves recognition and readability.
* shim-sev:syscall: Remove `Handler`
Remove the now obsolete `Handler` struct, which saves one indentation
level and provides the posssibility to move those functions in separate
modules, like `io`, `mem`, etc.
* shim-sev:syscall: Fix write syscall
Don't use `host_call.write()` but rather do a complete syscall.
`host_call.write()` should be used kernel internal only.
* shim-sev:syscall: Factor out `blk_to_host_virt`
The `blk_to_host_virt()` function factors out the often used conversion from
a `sallyport:Block` buffer address to the host virtual address.
> shim-sev: refactor, simplify, beautify the syscalls

- internal/shim-sev/src/syscall.rs
`rdx` is sometimes used as a secondary return value.
Because `rdx` is not marked as `clobber` for the musl syscall macro,
the original value has to be returned, if `rdx` is unused as a return
value.
To combat the use of the stack in `_syscall_enter` with `opt-level=0`,
reserve a little red zone on the stack for `#[cfg(debug_assertions)]`.
In `opt-level=3` the compiler does emit the correct assembly code
without using the stack.
This patch also adds a dummy path for the enarx syscalls, which can make
use of the second return value.
> shim-sev: handle multiple return values for syscalls

- src/sallyport/mod.rs
A syscall clobbers `rcx` and `r11`, which was not marked here.
> sallyport: syscall clobber `rcx` and `r11`

- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/handler.rs
- src/sallyport/mod.rs
Because `Cursor::alloc()` returns a `MaybeUninit` it can be marked as safe.
> sallyport: mark Cursor::alloc as safe

- src/sallyport/mod.rs
* sallyport: add `Cursor::copy_into_slice()`
This actually needs a decouple of lifetimes of `Cursor::alloc()`.
*  sallyport: give some return values a decoupled lifetime
Sometimes the lifetime of a return value has to be decoupled from the
parent object with a short lifetime.
Here `Cursor::alloc` and `Cursor::copy_from_slice` benefit from
returning references with a possible shorter lifetime than the original
`Cursor`.
> sallyport: add `Cursor::copy_into_slice()`

- .github/dependabot.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- internal/shim-sev/Cargo.lock
- internal/shim-sev/Cargo.toml
- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/Cargo.lock
- internal/shim-sgx/Cargo.toml
- internal/shim-sgx/src/event.rs
- internal/shim-sgx/src/handler.rs
- internal/syscall/Cargo.toml
- internal/syscall/LICENSE
- internal/syscall/src/lib.rs
- internal/untrusted/Cargo.toml
- internal/untrusted/LICENSE
- internal/untrusted/src/lib.rs
* feat(untrusted): Add untrusted crate
Adds a crate to validate
* `const *T`
* `mut *T`
* `const *[T]`
* `mut *[T]`
by checking the alignment and calling out to a shim specific
validator method, which should check, if the referenced memory
is in a valid address space.
Resolves: https://github.com/enarx/enarx/issues/630
Related: https://github.com/enarx/enarx-keepldr/issues/78
* feat(syscall): Add syscall crate
This crate unifies the syscall infrastructure in a common trait shared
between shims. An implementation of the `SyscallHandler` trait has to
implement the empty syscalls and can overwrite pre-implemented syscalls
with an optimized version.
This crate also should hold any Enarx specific syscall constants and type
definitions.
* refactor(shims): Use untrusted and syscall crates
Let …
> shims: Unify syscall handlers

- src/sallyport/mod.rs
If additional filedescriptors are open, the `syscall` test fails,
because it assumes, that the return value of dup() is 3.
This patch removes the hardcoded value and checks,
if the return value is greater 0 and then closes the dup'ed fd.
Fixes: https://github.com/enarx/enarx-keepldr/issues/135
> fix(sallyport): Don't hardcode dup'ed file descriptor value

- internal/syscall/src/lib.rs
While the address of the whole array should be the same
as the first element, don't make such assumptions and
use the pointer of the first element.
> fix(syscall): Use correct pointer for clock_gettime

- internal/shim-sev/src/syscall.rs
To clarify the hex output, prepend the hex numbers with `0x`.
Use the rust format parameter instead of manually specify `0x`
> fix(shim-sev): Prepend syscall trace args with `0x`

- Cargo.lock
- Cargo.toml
- tests/integration_tests.rs
The more tests we add the more pressure we're putting on the
SEV launch process. Let's serialize them to avoid spurrious
failures, otherwise we'll just be playing a game of adjusting
the timeout again and again.
edit: I'll be looking into ways to hasten the launch process as well.
I have a hunch that #134 might help... not sure.
> Serialize integration tests

- internal/sallyport/src/lib.rs
This doc section seems to be a leftover, when some module was called `proxy`.
> fix(sallyport): Remove obsolete doc section

- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/handler.rs
- internal/syscall/src/lib.rs
- src/backend/sgx/attestation.rs
- src/backend/sgx/mod.rs
- tests/bin/sgx_get_att_quote.c
- tests/integration_tests.rs
Closes #91 
This PR:
- Updates the function signature for `get_attestation()` in the internal `syscall` mod, the sev handler, and the sgx handler to pass the four parameters mentioned in #31 .
- Adds logic in the SGX shim handler to make two calls out to the host before returning a Quote to the code layer: one to request a TargetInfo from the host, and the second to request a Quote from the host. The first is a necessary prerequisite for the second.
- Adds an attestation mod in the sgx backend on the host side to handle proxied `get_att()` syscalls from the sgx shim. This currently returns synthetic values, but will communicate with the AESM daemon to get real TargetInfo and Quote values in the next PR.
- Adds logic in the sgx backend mod to route `get_att()` syscalls to the above …
> Stub in shim --> host implementation of get_att() for SGX

- internal/shim-sev/src/frame_allocator.rs
For better debugging, output the address in the panic message in
hexadecimal form.
> fix(shim-sev): Output address in hex on panic in get_virt_offset

- tests/integration_tests.rs
*  feat(tests): Better output on failure
The integration tests output very long `assert_eq` comparisons, if the
output doesn't match the expected. To reduce the clutter, only use
`assert_eq` if the size is smaller than 100 first, then assert on the
length and finally do the long `assert_eq`.
To indicate what assertion failed, add descriptive messages to the
`assert_eq` macros.
Also, in the case of no expected stderr, print out any stderr received,
to help debug any failures.
> feat(tests): Better output on failure

- internal/syscall/src/lib.rs
- src/sallyport/mod.rs
- tests/bin/read_udp.c
- tests/integration_tests.rs
*   fix(syscall): Read/Write in chunks of Block::buf_capacity
Read and Write from the host in chunks of `Block::buf_capacity()`,
if the requested length is greater.
While this might cause problems with blocking file descriptors,
it is very unlikely though.
*   fix(sallyport): Fix the sallyport block size
The sallyport block size was set 512 * 4096 bytes, whereas
the space was never allocated in the kvm backend.
This patch sets the capacity to hold at least a maximum UDP packet.
When multi-threading is implemented multiple buffers need to be
available for concurrent syscalls.
Related: https://github.com/enarx/enarx-keepldr/issues/156
Fixes: https://github.com/enarx/enarx-keepldr/issues/23
*   feat(tests): Add read_udp test
This test tries to read 65507 in one go.
It fails, if there was a …
> Fix the sallyport blocksize

- internal/shim-sev/src/main.rs
- internal/shim-sev/src/syscall.rs
- internal/shim-sev/src/usermode.rs
- internal/shim-sgx/src/entry.rs
Named parameters make reading `asm!()` blocks a lot easier and are less
error prone to changes made in the arguments.
> feat(shim-sev): Use named parameters in asm! blocks

- internal/shim-sev/src/syscall.rs
Do not leak the register contents of rcx and r11 to user space.
Also add more comments to clarify what is preserved by the called
function.
> fix(shim-sev): Clear rcx and r11 on syscall return

- .github/workflows/lint.yml
- src/backend/sgx/attestation.rs
Without `--all-features` not all modules are checked. Namely the `sgx`
backend was completely left out.
> fix(lint): Turn on all features with clippy lint

- .github/workflows/lint.yml
- src/backend/mod.rs
- src/binary/component.rs
- src/sallyport/mod.rs
Clippy check also individual backends with the other features disabled.
The uncovered clippy failures are also fixed in this PR.
> ci(clippy): Check clippy for single backends

- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/hostlib.rs
- internal/shim-sgx/src/event.rs
- internal/shim-sgx/src/handler.rs
- internal/shim-sgx/src/hostlib.rs
- internal/shim-sgx/src/start.S
- internal/syscall/src/lib.rs
- src/backend/kvm/vm/cpu.rs
- src/backend/sgx/mod.rs
- src/main.rs
- src/syscall/mod.rs
The syscall constants are spread all over the place and named
inconsistently. This patch fixes that.
> feat(syscall): Collect all syscall constants

- Cargo.lock
- Cargo.toml
- build.rs
- internal/shim-sgx/Cargo.lock
- internal/shim-sgx/Cargo.toml
- src/main.rs
- src/protobuf/aesm-proto.proto
- src/protobuf/mod.rs
We will need an updated version of the SGX dependency and we'll need to use Intel's `aesm-proto` file to generate Rust structures during build.
> Prepare some small changes for SGX attestation

- .github/workflows/test.yml
GitHub Actions will vacuously fail a CI job that uses this command. Just for now. [I am working on removing the affected step entirely](https://github.com/enarx/packet.com/pull/23).
Closes: https://github.com/enarx/enarx-keepldr/issues/83
> Remove deprecated command

- tests/bin/enarx.h
- tests/bin/get_att.c
- tests/bin/sgx_get_att_quote.c
- Factor out TEE enum to its own header
- Return success if not running on SGX in sgx_get_att_quote test
> Fix spurious failure in sgx_get_att_quote test if not running on SGX

- .github/workflows/test.yml
Only enable the specific test backend feature
and don't enable default backends.
> ci(test): Run "cargo test" without default features

- Cargo.lock
- Cargo.toml
- src/backend/sev/builder.rs
- src/backend/sev/mod.rs
- src/backend/sev/unattested_launch.rs
- Bump sev to 66248f21
- Implement remote AMD SEV attestation protocol
Depends on: https://github.com/enarx/sev/pull/33 before I can unmark this as a draft as the `Cargo.toml` points at my personal `sev` repo.
Helpful for understanding the protocol: https://github.com/enarx/enarx-keepldr/wiki/AMD-SEV-Remote-Attestation-Protocol
> Implement AMD SEV Remote Attestation + builtin synthetic client implementation for unattested launch

- build.rs
- internal/shim-sev/src/payload.rs
- internal/shim-sev/src/usermode.rs
- src/main.rs
*   fix(keepldr): suppress clippy warnings
Suppress clippy warnings about `Result<()>`, where the functions never
return an `Err()` for now.
*   fix(shim-sev): Function crt0setup does not need Result as return
`crt0setup()` never returns an `Err()`, so remove `Result` from the
return parameter, otherwise clippy will complain.
*   fix(build): Remove unnecessary return value
`rerun_src()` doesn't need a return value, so remove it, because clippy
will complain.
*   fix(shim-sev): remove `naked` attribute from usermode fn
The `#[naked]` caused a rustc segfault. Remove it, because it was the
wrong attribute anyway.
> fix build on nightly

- tests/integration_tests.rs
`miri` can't call libc functions, so ignore the whole integration_tests.
> test(integration): ignore integration_tests for miri

- internal/shim-sev/src/asm.rs
- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/hostlib.rs
- src/backend/kvm/mod.rs
- src/backend/kvm/vm/builder.rs
- src/backend/kvm/vm/cpu.rs
- src/backend/kvm/vm/mod.rs
- src/backend/sev/mod.rs
*   feat(shim-sev): Use multiple sallyport::Block
Because the setup area is limited in memory size, not each thread can
get its own `sallyport::Block` to communicate with the host.
Therefore a pool of blocks is reserved, which can be dynamically used
by the shim indicating the actual block via the value passed in the
IOPort.
A future extension could reserve additional blocks via a enarx specific
syscall.
This patch also removes the now obsolete `backend::kvm::vm::Builder::Config`.
Fixes: https://github.com/enarx/enarx-keepldr/issues/156
*   fix(shim-sev): rename ALIGN_ABOVE_2MB
Rename `ALIGN_ABOVE_2MB` to `MAX_SETUP_SIZE` to reflect its meaning.
> Sev concurrent syscalls

- internal/shim-sgx/src/handler.rs
- internal/syscall/src/lib.rs
- src/sallyport/mod.rs
*   fix(sallyport): mark copy_into_slice unsafe
`Cursor::copy_into_slice` has to be unsafe, otherwise it is possible to
fill in a slice of e.g. bools with invalid values using safe rust code.
This patch also adds a test calling `Cursor::copy_into_slice()` and
simplifies the method by removing a parameter and calling existing
methods.
> fix(sallyport): mark copy_into_slice unsafe

- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/handler.rs
- internal/syscall/src/lib.rs
Add a method to the `SyscallHandler` to report an unknown syscall,
similar to `trace()`.
> feat(syscall): Report an unknown syscall

- internal/syscall/src/lib.rs
Add missing `trace()` debug calls to the some syscalls.
This needs `fcntl` to take `&mut self` to call `self.trace()`.
> feat(syscall): Add missing trace to syscalls

- tests/integration_tests.rs
Factor out `fn assert_eq_slice()` to compare slices.
It will be used by upcoming tests.
> refactor(test): Refactor the comparison of slices

- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/handler.rs
- internal/syscall/src/lib.rs
The `SyscallHandler::translate_shim_to_host_addr` previously took `self`
as a parameter. This causes problems, if other methods take a mutable
`self`. To avoid clashes, remove `self` from `translate_shim_to_host_addr`.
Also return `usize`, to prevent usage as a real pointer, because it's
a host virtual address, which is most likely not the same address space
(except for SGX).
> feat(syscall): translate_shim_to_host_addr does not need `self`

- internal/shim-sev/src/attestation.rs
- internal/shim-sev/src/hostlib.rs
- internal/shim-sev/src/main.rs
- internal/shim-sev/src/syscall.rs
- src/backend/kvm/mod.rs
- src/backend/kvm/vm/builder.rs
- src/backend/sev/builder.rs
Inject the secret and provide it with the get_attestation call.
Fixes: https://github.com/enarx/enarx-keepldr/issues/159
> feat(shim-sev): Implement get_attestation for SEV

- Cargo.lock
- Cargo.toml
- src/backend/kvm/mod.rs
- src/backend/kvm/vm/builder.rs
- src/backend/mod.rs
- src/backend/sev/builder.rs
- src/backend/sev/mod.rs
- src/backend/sgx/mod.rs
- src/main.rs
*   feat(keepldr): Measure the contents of the keep for SEV
This patch adds a new command `measure`, which produces a measurement on
the deployed keep and outputs relevant data as a json record,
which can be used by clients to validate a keep.
This patch implements the measurement for the SEV backend.
> feat(keepldr): Measure the contents of the keep for SEV

- BUILD.md
- README.md
- src/main.rs
* Move build instructions to BUILD.md
* Add a note about gcc
* Add instructions for CentOS 8
> Factor out build instructions it its own file + add some other notes

- internal/shim-sev/src/start.rs
- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/enclave.rs
Current nightly does not accept `extern "Rust"` (which is the default)
for naked functions. It really should be `extern "custom"`, but that
does not exist, so choose the well known "sysv64" ABI.
> fix(shim): naked functions need ABI specifier

- internal/shim-sev/src/addr.rs
- internal/shim-sev/src/allocator.rs
- internal/shim-sev/src/main.rs
- internal/shim-sev/src/payload.rs
- internal/shim-sev/src/shim_stack.rs
- internal/shim-sev/src/syscall.rs
This patch prepares for turning the frame_allocator into
a general purpose allocator.
> feat(shim-sev): rename frame_allocator -> allocator

- internal/shim-sev/src/payload.rs
Reduce the stack size to that of a default linux process.
> fix(shim-sev): reduce payload stack size to 8MB

- internal/shim-sev/src/main.rs
`force_unlock_read()` panics, if the RWLock is not locked readable,
which is the case, if it is locked writeable.
Therefore only call `force_unlock_write()`, if a read lock could not be
acquired.
> fix(shim-sev): fix the panic handling of locked objects

- internal/shim-sev/src/gdt.rs
Increase the `shim-sev` stack size to the size of the default Linux
stack size of 8MB. Decrease the *currently* unused exception stack
size.
> fix(shim-sev): increase stack size, decrease exception stack size

- internal/shim-sev/src/addr.rs
- internal/shim-sev/src/pagetables.rs
- internal/shim-sev/src/start.rs
While experimenting with the allocator, I found the page tables to be setup incorrectly.
Here are two patches to fix that:
*   fix(shim-sev): Fix page table entries offset page table
The huge pages for the offset page table used 2 GiB steps, instead
of 1 GiB, which resulted in invalid mappings.
*   fix(shim-sev): Fix C-bit setup in start assembler
The C-bit correction in assembler used `mov` instead
of `or` to set the C-bit. This cleared existing bits
and resulted in invalid page table entries.
> shim-sev: two fixes for the page tables

- src/backend/kvm/mod.rs
- src/backend/kvm/vm/builder.rs
- src/backend/kvm/vm/cpu.rs
- src/backend/kvm/vm/image/mod.rs
- src/backend/kvm/vm/image/x86.rs
- src/backend/kvm/vm/mod.rs
- src/backend/mod.rs
- src/backend/sev/builder.rs
- src/backend/sev/mod.rs
- src/backend/sgx/mod.rs
- src/main.rs
The loader is having some growing pains. Let's rearrange some stuff to make it easier to add other stuff.
* Update builder address translation hook to return a closure
* Express syscall blocks as Span for Vm
* Factor out VM construction into modular components
* Move measurement functionality out of Builder::Hook
* Propagate measurement JSON to subcommand so it can print it
> Refactor VM builder modules

- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/handler.rs
- internal/syscall/src/lib.rs
Use normal sallyport syscall proxying for `exit()` and `exit_group()`
for all shims.
> feat(shim-sev): Refactor exit() and exit_group()

- Cargo.lock
- Cargo.toml
- src/backend/kvm/mod.rs
- src/backend/kvm/vm/builder.rs
- src/backend/kvm/vm/cpu.rs
- src/backend/kvm/vm/mod.rs
- src/backend/kvm/vm/personality.rs
- src/backend/sev/ioctl/mod.rs
- src/backend/sev/ioctl/types.rs
- src/backend/sev/mod.rs
- src/backend/sev/personality.rs
- src/backend/sev/runtime.rs
- tests/bin/memspike.rs
- tests/integration_tests.rs
* Add a VM personality framework
* Add support for runtime SEV memory pinning
The included `memspike` integration test can be used to check that pages are getting pinned when ballooning (look for the successful `KVM_MEMORY_ENCRYPT_REG_REGION` near the bottom where we see additional memory getting hotplugged):
```console
strace -Te trace=ioctl --decode-fds=path ./target/debug/enarx-keepldr exec target/debug/build/enarx-keepldr-1667cd10683671e6/out/bin/memspike
ioctl(3</dev/kvm>, KVM_GET_API_VERSION, 0) = 12 <0.000006>
ioctl(5</dev/kvm>, KVM_CREATE_VM, 0)    = 6<anon_inode:kvm-vm> <0.000275>
ioctl(5</dev/kvm>, KVM_GET_VCPU_MMAP_SIZE, 0) = 12288 <0.000005>
ioctl(6<anon_inode:kvm-vm>, KVM_SET_USER_MEMORY_REGION, {slot=0, flags=0, guest_phys_addr=0, memory_size=39845888, …
```
> Add VM runtime personalities with its first event: memory pinning when ballooning

- internal/shim-sev/src/hostlib.rs
This reverts commit 7b6e23eb00d644120ddadfbf76b54ac0b7ebf3d5.
Apparently this patch causes 4 more seconds on VM startup time.
Measuring the `exit_zero` integration_tests test gives:
```
❯ hyperfine "target/release/deps/integration_tests-b64a094b34c0b68f exit_zero"
Benchmark #1: target/release/deps/integration_tests-b64a094b34c0b68f exit_zero
Time (mean ± σ):      4.720 s ±  0.012 s    [User: 15.1 ms, System: 49.1 ms]
Range (min … max):    4.687 s …  4.729 s    10 runs
```
And with this patch reverted:
```
❯ hyperfine "target/release/deps/integration_tests-b64a094b34c0b68f exit_zero"
Benchmark #1: target/release/deps/integration_tests-b64a094b34c0b68f exit_zero
Time (mean ± σ):     793.7 ms ±   0.4 ms    [User: 12.7 ms, System: 45.5 ms]
Range (min … max):   793.1 ms … 794.4 ms    10 runs …
```
> Revert "fix(shim-sev): add an addition 32MB to the memory"

- src/backend/kvm/vm/builder.rs
Limit the initial memory space to a minimum and don't align up
needlessly. VM encryption speed of 8MB/s is extremely slow.
Before:
```console
❯ hyperfine "target/release/enarx-keepldr exec ./target/release/build/enarx-keepldr*/out/bin/exit_zero "
Benchmark #1: target/release/enarx-keepldr exec ./target/release/build/enarx-keepldr*/out/bin/exit_zero
Time (mean ± σ):     769.2 ms ±   0.8 ms    [User: 12.2 ms, System: 20.8 ms]
Range (min … max):   768.2 ms … 770.8 ms    10 runs
```
After:
```
❯ hyperfine "target/release/enarx-keepldr exec ./target/release/build/enarx-keepldr*/out/bin/exit_zero "
Benchmark #1: target/release/enarx-keepldr exec ./target/release/build/enarx-keepldr*/out/bin/exit_zero
Time (mean ± σ):     537.6 ms ±   3.1 ms    [User: 11.3 ms, System: 20.2 ms]
Range (min … max): …
```
> fix(loader): Minimize memory size

- internal/shim-sev/src/allocator.rs
- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/main.rs
- internal/shim-sev/src/spin.rs
- internal/shim-sev/src/syscall.rs
This patch enables us to communicate with the Host via multiple
sallyport::Blocks in parallel.
A global HostCallAllocator is added, where one can allocate one
sallyport::Block encapsulated in a `HostCall` type.
This patch also adds the `spin` module, which wraps `spinning::Mutex`
and `spinning::RWLock`, so we can use `impl` on our own types.
> feat(shim-sev): Use multiple sallyport blocks in parallel

- Cargo.lock
- Cargo.toml
- tests/bin/unix_echo.rs
- tests/integration_tests.rs
Use the `tmpdir` crate to create a temporary directory, which is removed
after the test ran. Even, if the drop function is not called, the next
test run, will produce a new unique name for the directory and will not
clash with previous leftovers.
> test(unix_echo): remove socket files after test

- build.rs
Otherwise CI fails with its newly updated clippy definitions
> Take clippy suggestion to use &Path instead of &PathBuf

- Cargo.lock
- internal/shim-sev/Cargo.lock
- internal/shim-sgx/Cargo.lock
- src/backend/sgx/attestation.rs
* fix: update dependencies for cargo deny
cargo deny complains about smallvec 1.5.1 having a security
vulnerability.
ID: RUSTSEC-2021-0003
Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0003
A bug in the `SmallVec::insert_many` method caused it to allocate a buffer
that was smaller than needed.  It then wrote past the end of the buffer,
causing a buffer overflow and memory corruption on the heap.
A manual `cargo update` updates the deps of the deps, so a fixed version
is used in the end.
* fix(backend/sgx): use Message::parse_from_bytes
```    
error: use of deprecated function `protobuf::parse_from_bytes`: Use Message::parse_from_bytes instead
Error:   --> src/backend/sgx/attestation.rs:69:32
|
69 |     let mut pb_msg: Response = protobuf::parse_from_bytes(&res_bytes)?;
| …
```
> fix build environment for clippy and cargo-deny

- internal/shim-sev/Cargo.lock
- internal/shim-sev/Cargo.toml
- internal/shim-sev/src/addr.rs
- internal/shim-sev/src/allocator.rs
- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/hostlib.rs
- internal/shim-sev/src/hostmap.rs
- internal/shim-sev/src/main.rs
- internal/shim-sev/src/pagetables.rs
- internal/shim-sev/src/print.rs
- internal/shim-sev/src/syscall.rs
- internal/shim-sgx/src/handler.rs
- internal/syscall/src/lib.rs
- src/backend/kvm/vm/cpu.rs
- tests/bin/memory_stress_test.rs
- tests/integration_tests.rs
*   feat(shim-sev): switch to a linked list allocator
The old allocator was a bump allocator, which could not free unused memory.
This patch uses the linked_list_allocator crate to back the management
of the free memory.
The mapping of the host virtual addresses to shim physical addresses was moved
into its own `HostMap` type.
*   feat(shim-sev): implement the munmap syscall
The old unmap syscall was only a stub, because the old allocator
could not free memory.
Resolves: https://github.com/enarx/enarx-keepldr/issues/205
> shim-sev: Introduce a new allocator and the munmap syscall

- src/backend/kvm/mod.rs
- src/backend/kvm/vm/builder.rs
- src/backend/kvm/vm/measure.rs
- src/backend/kvm/vm/mod.rs
- src/backend/sev/builder.rs
- src/backend/sev/mod.rs
This is the final hook where the SEV backend will encrypt
the address space. Taking the measurement post-encryption
is not what we want. We want the measurement of the state
_before_ encryption; otherwise the measurement will change
with each launch even though the binaries are the same.
Closes #282 
**Before**:
```console
$ ENARX_BACKEND=sev ./target/debug/enarx-keepldr report $WASMLDR
{ "backend": "sev", "sha256": [136, 239, 163, 55, 213, 146, 79, 160, 137, 181, 165, 140, 132, 105, 224, 21, 181, 235, 88, 69, 118, 155, 74, 149, 184, 234, 5, 83, 75, 99, 201, 226] }
$ ENARX_BACKEND=sev ./target/debug/enarx-keepldr report $WASMLDR
{ "backend": "sev", "sha256": [240, 172, 207, 232, 1, 64, 242, 35, 41, 2, 168, 42, 20, 157, 13, 14, 228, 117, 72, …
```
> Measure VM address space before code_loaded hook

- .github/workflows/test.yml
Closes https://github.com/enarx/sev/issues/25.
Drafted until Rome has been re-kicked since the kickstart file is responsible for caching the certificate chain and mounting it into the GHA container.
> Remove unnecessary certificate chain caching step

- src/backend/sgx/attestation.rs
- src/syscall/mod.rs
- tests/bin/get_att.c
- tests/bin/sgx_get_att_quote.c
The V3 Quote is necessary for the DCAP attestation that we are using.
I'm hoping to eventually do a bit more cleanup around error handling, etc.
In this PR:
- Refactor of SGX attestation code (factor out setting protobuf message fields and sending and receiving
protobuf messages to remove redundancy before adding extra API calls)
- Moving the AESM connection detection (and return of dummy values if no connection) to be done only once (again to remove redundancy before adding more API calls)
- Adding extra API necessary for V3: getting attestation key ID
- Adding extra API necessary for V3: getting attestation key size
- Updating API calls to get V3 Quote
> Update SGX attestation to get V3 Quote

- src/backend/sgx/mod.rs
error: calls to `push` immediately after creation
```
--> src/backend/sgx/mod.rs:65:9
|
65 | /         let mut data = vec![];
66 | |
67 | |         data.push(data::dev_sgx_enclave());
| |___________________________________________^
```
help: consider using the `vec![]` macro: `let mut data = vec![..];`
> fix(backend/sgx): satisfy clippy

- src/backend/sev/builder.rs
- src/backend/sev/mod.rs
- src/backend/sev/unattested_launch.rs
*  feat(backend/sev): add context message to `sev::cached_chain::get()?`
```
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`
Caused by:
Permission denied (os error 13)
```
* fix(sev): print user friendly attestation_bridge errors
```
Error: Failed to read cached certification chain from `/var/cache/amd-sev/chain`
Caused by:
Permission denied (os error 13)
attestation_bridge error: failed to deserialize expected certificate chain
```
> fix: validate SEV cert chain and improve error output

- internal/shim-sev/src/syscall.rs
- src/backend/sev/unattested_launch.rs
- tests/bin/sev_get_att_quote.c
- tests/integration_tests.rs
Inject a fake secret in the unattested launch and test for it in the
integration tests.
> test: add sev_get_att_quote

- internal/shim-sgx/src/handler.rs
- src/backend/sgx/attestation.rs
- tests/bin/get_att.c
- tests/bin/sgx_get_att_quote.c
- tests/bin/sgx_get_att_quote_size.c
- tests/integration_tests.rs
In this PR:
- Return a Quote length to the code layer if nonce value is NULL
- Embed hash into ReportData if nonce (hash) value is non-NULL and 64 in length
Resolves #313 
Resolves enarx/enarx#918
> Return Quote len and embed ReportData in SGX get_attestation()

- tests/bin/sgx_get_att_quote.c
Apparently the C compiler doesn't like the for loop the other way.
> Fix C warning

- internal/shim-sev/src/allocator.rs
- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/hostmap.rs
- internal/shim-sev/src/spin.rs
clippy complains with:
```
error: name `RWLocked` contains a capitalized acronym
Error:   --> src/spin.rs:29:12
|
29 | pub struct RWLocked<A> {
|            ^^^^^^^^ help: consider making the acronym lowercase,
except the initial letter
(notice the capitalization): `RwLocked`
```
> fix(shim-sev): rename `RWLocked` to `RwLocked`

- tests/bin/libc.h
- tests/bin/uname.c
- tests/integration_tests.rs
This will close #340. Currently I'm getting odd behavior, where `strcmp` isn't recognized in `tests/bin/uname.c`, even though I've included `#include <string.h>` in `tests/bin/libc.h`.
The same code in `tests/bin/uname.c` compiles and runs as expected, when the headers below are included directly, rather than in `libc.h`, and the code is compiled standalone, outside of the test harness. I confess I'm stumped.
```
#include <errno.h>
#include <sys/utsname.h>
#include <string.h>
```
Edit: @haraldh explained the issue. I reimplemented `strcmp` as a function.
> Implement uname() syscall test

- Cargo.lock
- Cargo.toml
- helper/parse-trace.sh
- internal/shim-sev/Cargo.lock
- internal/shim-sev/src/asm.rs
- internal/shim-sev/src/gdt.rs
- internal/shim-sgx/Cargo.lock
- internal/shim-sgx/Cargo.toml
- internal/shim-sgx/src/handler.rs
- src/backend/sgx/attestation.rs
* error: invalid register rbx: rbx is used internally by LLVM and cannot be used as an operand for inline asm
See:  rust-lang/rust#84658 (comment) and the [commit](https://github.com/rust-lang/rust/pull/84658/files#diff-d7283132d97a993fad4e2d491ac883dbce4e17fe248cdf37fa3f9334e2a5a115)
* fix(sev): unaligned reference to packed field
* fix(sgx): reference that is immediately dereferenced by the compiler
> Make enarx-keepldr compile again

- helper/parse-trace.sh
> fix: let parse-trace.sh work with shim kernel addresses

- internal/shim-sev/src/hostcall.rs
- internal/shim-sev/src/main.rs
- internal/shim-sev/src/payload.rs
- internal/shim-sev/src/syscall.rs
- internal/shim-sev/src/usermode.rs
> fix: remove last `;` from noreturn functions

- internal/shim-sev/src/main.rs
- internal/shim-sev/src/start.rs
Remove the `entry_point` macro and reference the `_start_main` rust
function symbol properly from the `_start` asm block.
> fix(shim-sev): reference the last symbol outstanding

- internal/shim-sev/src/start.rs
Clear the overflow flag, before using `adox`, otherwise it would be
added by accident.
Also, remove redundant usage of `r15`.
>  fix(shim-sev): clear OF before adox 

- src/binary/component.rs
> feat(loader): let `Component::from_bytes()` be generic with `AsRef`

- internal/shim-sgx/src/enclave.rs
- internal/shim-sgx/src/entry.rs
- internal/shim-sgx/src/event.rs
- internal/shim-sgx/src/handler.rs
- internal/shim-sgx/src/hostlib.rs
- internal/shim-sgx/src/main.rs
- src/backend/sgx/mod.rs
This contains some pretty big refactoring in preparation for the "elf loader" transition. The biggest win is that we throw a way a big chunk of assembly code. The resulting code is easier to use, easier to reason about and less error prone.
> Refactor code for ergonomics and assembly reduction

- Cargo.lock
- Cargo.toml
- src/backend/sgx/enclave/builder.rs
- src/backend/sgx/enclave/execute.rs
- src/backend/sgx/enclave/ioctls.rs
- src/backend/sgx/enclave/mod.rs
- src/backend/sgx/mod.rs
I performed a dependency analysis of the types from the sgx crate. These
types are only used in this crate. Further, they encapsulate some
enarx-specific behavior and probably aren't useful outside enarx.
Therefore, I move them from the sgx crate into here. A separate PR will
remove these types from the sgx crate.
Signed-off-by: Nathaniel McCallum <nathaniel@profian.com>
> Move enclave creation structures from sgx
